  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.14
    env:
      TZ: "America/Jamaica"
    service:
      main:
        type: LoadBalancer
    persistence:
      data:
        enabled: true
        existingClaim: mqtt-config-v1
